# Generated by Django 4.2.4 on 2023-08-17 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('image', 'Image')], max_length=10, verbose_name='File Type'),
        ),
    ]
